modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "brainier_bees"
version = "${version}"
displayName = "Brainier Bees"
authors = "dopadream"
description = '''
Refactors Bee behavior using Mojang's Brain AI system
'''
#logoFile = ""

[[dependencies.brainier_bees]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brainier_bees]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brainier_bees]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "brainier_bees.mixins.json"
